version: "3"
services:
    app:
        container_name: edibles_container
        restart: always
        build: .
        ports:
            - "8080:4000"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mvertes/alpine-mongo
        ports:
            - "27018:27017"
            

