apiVersion: v1
kind: Service
metadata:
  name: edibles-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: edibles-app